version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

  auth:
    image: andrianovartemii/gm-test-task-auth-generator:latest
    ports:
      - "8080:8080"
    environment:
      AUTH_TOKEN_LIFETIME: 2
    networks:
      - my-network

  gateway:
    build:
      context: ./gateway
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
     - rabbitmq
    networks:
      - my-network

  store:
    build:
      context: ./store
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - my-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    env_file:
      - dev.env
    networks:
      - my-network
    ports:
      - "5432:5432"
networks:
  my-network: